### ISSUE TITLE
Problems with win7 and win10

### ISSUE THREAD

**Issue by cameyo42** [daansystems/lispide#1]
I have installed the last version of LispIDE (2018).
I have two different problems:
- on windows 7 the program starts, but crash when opening a new document
- on windows 10 the program do not starts.
Note: LispIDE (2010) works in both win7 and win10.
Thanks for your work.

**Comment by daansystems** [comment]
Can you please check the new installer in the installer dir?

**Comment by cameyo42** [comment]
The new installer works, but i can't use the shortcut "shift-enter", "alt-enter" and "control-enter".
These commands works only by using the menu item.
I have compiled the source with vs2017 with the same results.
Thanks.

**Comment by daansystems** [comment]
Please check v20220906.08, if the issue persists please create a new one.
