### ISSUE TITLE
crash on win8.1

### ISSUE THREAD

**Issue by llbook** [daansystems/lispide#2]
LispIde (2018 precompiled): crashes immediately after startup

LispIde(2010 precompiled from your homepage): only editor working; no contact with any lisp or scheme program (sbcl; ECL; ChezScheme)

**Comment by daansystems** [comment]
Did you compile LispIDE with the latest Visual Studio? Can you compile a debug version and check where it crashes?

**Comment by daansystems** [comment]
Can you please check the new installer in the installer dir?

**Comment by llbook** [comment]
Now LispIde (2018 precompiled) no longer crashes, but still no contact with either sbc, ecl or chez scheme. How is that contact supposed to be established? I have indicated the respective .exe-files in the 'Settings", I have clicked on the 'Reset Lisp' and 'Send To Lisp' buttons, I have tried with and without lisp already running - still no luck.
As to compiling with Visual Studio: I no longer have VS; I quite liked it some 10 years ago, but now it has become a grotesque monster of several gigabytes. I wish I could get my hands on an older, more reasonable Express Edition, but Microsoft does not offer those anymore and unfortunately I no longer have the installation file from back when. I now use the gnu compiler with msys2 instead.

**Comment by daansystems** [comment]
Does going to Settings -> Set Lisp Path, then point it to sbcl.exe or a custom .bat file not work?

**Comment by llbook** [comment]
No, it does not.

**Comment by daansystems** [comment]
Please check v20220906.08, If this issue still persists please create a new issue
